version: '3.8'

services:
  trading-bot:
    build: .
    container_name: kucoin-trading-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
