version: '3.8'

services:
  # PostgreSQL database for trade history and analytics
  postgres:
    image: postgres:15-alpine
    container_name: rad_postgres
    environment:
      POSTGRES_DB: trading_bot
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Trading bot application
  trading-bot:
    build: .
    container_name: kucoin-trading-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Database connection
      DATABASE_URL: postgresql://trader:${POSTGRES_PASSWORD:-changeme}@postgres:5432/trading_bot
      # Dashboard
      DASHBOARD_PORT: ${DASHBOARD_PORT:-5000}
      ENABLE_DASHBOARD: ${ENABLE_DASHBOARD:-false}
    ports:
      - "${DASHBOARD_PORT:-5000}:5000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - bot_data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local
  bot_data:
    driver: local

networks:
  default:
    name: rad_trading_network
