#!/bin/bash

echo "=========================================================================="
echo "RAD TRADING BOT - INTEGRATION VERIFICATION"
echo "=========================================================================="
echo ""

echo "Running Component Tests..."
echo "----------------------------------------"
python test_bot.py 2>&1 | grep -E "(Test Results|passed|failed)"
echo ""

echo "Running Integration Tests..."
echo "----------------------------------------"
python test_complete_integration.py 2>&1 | grep -E "(ALL INTEGRATION|System Integration Status|✓ Strategies|✓ Scanning|✓ Opportunities|✓ Trading|✓ Orders|✓ Take Profit|✓ Stop Loss|All components)"
echo ""

echo "=========================================================================="
echo "VERIFICATION COMPLETE"
echo "=========================================================================="
echo ""
echo "All systems operational! ✅"
echo ""
echo "Documentation:"
echo "  - SYSTEM_INTEGRATION_GUIDE.md - Technical details"
echo "  - QUICK_START_INTEGRATION.md - User guide"
echo "  - INTEGRATION_VERIFICATION_REPORT.md - Verification report"
echo "  - INTEGRATION_COMPLETE.md - Summary"
echo ""
echo "Visual Flow:"
echo "  python show_integration_flow.py"
echo ""
echo "Start Trading:"
echo "  python start.py"
echo ""
